// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd5PQPpyShazZZ1e7f5q1ri0mpN2hUaX0',
    appId: '1:677788921135:web:344190ae85b6211defc5da',
    messagingSenderId: '677788921135',
    projectId: 'project04-1774e',
    authDomain: 'project04-1774e.firebaseapp.com',
    storageBucket: 'project04-1774e.firebasestorage.app',
    measurementId: 'G-JG7FG6LSG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0Zz6Klg4xInX2xi5lLydEfHVOzBZO84',
    appId: '1:677788921135:android:4a111599477fb0c8efc5da',
    messagingSenderId: '677788921135',
    projectId: 'project04-1774e',
    storageBucket: 'project04-1774e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2j1_nP4016D9zLeyL6y-osV0xDJZ5Fkw',
    appId: '1:677788921135:ios:f6c143b45d4d52e0efc5da',
    messagingSenderId: '677788921135',
    projectId: 'project04-1774e',
    storageBucket: 'project04-1774e.firebasestorage.app',
    iosBundleId: 'com.example.powergymMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2j1_nP4016D9zLeyL6y-osV0xDJZ5Fkw',
    appId: '1:677788921135:ios:f6c143b45d4d52e0efc5da',
    messagingSenderId: '677788921135',
    projectId: 'project04-1774e',
    storageBucket: 'project04-1774e.firebasestorage.app',
    iosBundleId: 'com.example.powergymMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd5PQPpyShazZZ1e7f5q1ri0mpN2hUaX0',
    appId: '1:677788921135:web:7a625a7d0d44cd1fefc5da',
    messagingSenderId: '677788921135',
    projectId: 'project04-1774e',
    authDomain: 'project04-1774e.firebaseapp.com',
    storageBucket: 'project04-1774e.firebasestorage.app',
    measurementId: 'G-24SF043SV8',
  );
}
